# Generated by Django 4.0.7 on 2022-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_historicaluser_avatar_remove_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
