# Generated by Django 4.0.7 on 2022-10-15 23:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=60)),
                (
                    "link",
                    models.URLField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a fucking valid URL",
                                regex="/^(https?:\\/\\/|mailto\\:).*\\.(com|org|net)\\.*$/",
                            )
                        ]
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome v5 icon link. (Optional)", max_length=40, null=True
                    ),
                ),
                ("is_mailer", models.BooleanField(default=False, help_text="Whether link is an email link")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
