# Generated by Django 4.0.7 on 2022-10-16 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_socialaccount_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
