# Generated by Django 4.0.7 on 2022-10-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_socialaccount_link_alter_socialaccount_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialaccount",
            old_name="is_mailer",
            new_name="is_email",
        ),
    ]
