# Generated by Django 4.0.7 on 2022-11-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_rename_is_mailer_socialaccount_is_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.URLField(
                default="https://github.com/cbedroid/personal-portfolio/raw/docs-storage/content/images/default_avatar.webp",
                help_text="Avatar url. (not required)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(default="User profile description", max_length=1000),
        ),
    ]
