# Generated by Django 4.0.7 on 2022-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_skill_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Programming Languages, technologies...etc", max_length=20, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.TextField(max_length=500)),
                ("video", models.URLField(help_text="Video preview link for project")),
                ("link", models.URLField(blank=True, help_text="Project's website link")),
                ("technology", models.ManyToManyField(to="core.technology")),
            ],
        ),
    ]
