# Generated by Django 4.0.7 on 2022-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_technology_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="image",
            field=models.URLField(blank=True, help_text="Technology image url"),
        ),
        migrations.AddField(
            model_name="technology",
            name="link",
            field=models.URLField(blank=True, help_text="Technology website url"),
        ),
    ]
