# Generated by Django 4.0.7 on 2022-09-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_technology_image_technology_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=800),
        ),
    ]
