# Generated by Django 4.0.7 on 2022-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(related_name="project", to="core.technology"),
        ),
    ]
