# Generated by Django 4.0.7 on 2022-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_project_technology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.ManyToManyField(to="core.technology"),
        ),
    ]
