# Generated by Django 4.0.7 on 2022-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_project_technology"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="rate",
            field=models.PositiveIntegerField(
                default=25, help_text="Experience level from 0 - 100"
            ),
        ),
    ]
