# Generated by Django 4.0.7 on 2022-10-11 06:09

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 10, 11, 6, 9, 29, 68917, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
