# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD Test Backend Application

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - master

jobs:
  testing:
    name: Linting, Format and Django test
    runs-on: ubuntu-latest

    env:
      DEBUG: 1
      SECRET_KEY: super_secret_test_key
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 *
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: github_actions
      SQL_USER: github
      SQL_PASSWORD: github
      SQL_HOST: 127.0.0.1
      SQL_PORT: 5432

    services:
      postgres:
        image: postgres:9.6.22-buster
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: github
          POSTGRES_DB: github_actions
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.15
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: Install apt prerequisites
        run: apt-get install python-dev libpq-dev tar

      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install --no-cache -r ./backend/requirements.txt
          pip install --no-cache Django==3.2.12

      - name: Running Django migrations
        run: |
          export DJANGO_SETTINGS_MODULE=portfolio.settings
          backend/manage.py makemigrations
          backend/manage.py migrate

      - name: Linting and Format Code
        run: pre-commit run --all-files

      - name: Running Django Test
        run: ./backend/manage.py test

  # End QA
